
# Application identity
spring.application.name=Institute_Pagination

spring.datasource.url=jdbc:postgresql://ep-square-lab-aoyxa9xl-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_TmFc9vu8qnlZ
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
